FRONTIER_MSG = 1
BLOCKS_REQ_MSG = 2
MULTI_BLOCKS_MSG = 3
BLOCK_MSG = 4
BLOCK_CAST_MSG = 5
AUDIT_PROOFS_REQ_MSG = 6
AUDIT_PROOFS_MSG = 7
STATE_REQ_MSG = 8
STATE_RESP_MSG = 9
SUBS_MSG = 10
STATE_BY_HASH_REQ_MSG = 11
STATE_BY_HASH_RESP_MSG = 12

COMMUNITY_CACHE = u"community_sync"
